Add classes
zieeco/awesome-book pull request #2
Opened 2021-09-22 13:49 UTC by zieeco

# Awesome Books: Refactor to use classes
**In this milestone, I and my partner achieved the following**
- Refactored the awesome book to use classes in the main.js file
- Ensured there were no linters error

2021-09-22 14:45 UTC, Georjane requested changes
### Hello, Team @zieeco and @Kingstalux, ✋🏽 

Good job so far! Your project works perfectly. You have a very professional Readme file, your PR is professional and you have a good mastery of git-flow. Your linters are all passing, I applaud that too.
However, we have a few more changes to make in order to meet all requirements for this project but you are almost there!

## Required Changes ♻️
_Check the comments under the review._

Cheers and Happy coding! 💻 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. 🤝 

_Code Reviewer
**[Jane](https://witahgeorjane.tech/)**_

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2021-09-22 14:45 UTC, Georjane commented on main.js
>  let books = [];
- [ ] Can you please initialize this books array inside your class books. For example
```
class Books {
  constructor() {
    this.books = [];
  }
...
}
```
Remember this is a project requirement
![image](https://user-images.githubusercontent.com/60772732/134365638-e9ed57fb-6e29-4623-a030-daa3e202953d.png)

2021-09-23 08:39 UTC, Kingstalux commented on main.js
>  let books = [];
Okay thanks, we've implemented that.

2021-09-23 08:46 UTC, rloterh commented on main.js
>  let books = [];
This issue is well resolved! ✔️

2021-09-23 08:47 UTC, rloterh approved these changes
## Status: Approved :heavy_check_mark:

Hi Isaac, 

Your project is complete! Great job for making the necessary changes recommended by the previous reviewer(s). There is nothing else to say other than... it's time to merge it 🍾:shipit:.
Congratulations! 🎉🥂

<br>
Cheers and Happy coding!👏 💻 🍷 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have 1 more limited review per this project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-09-23 08:48 UTC, merged